import type { Metadata } from "next";
import "./globals.css";
import NeonBackground from "@/components/NeonBackground";
import { Toaster } from "sonner";
import { CursorTracker } from "@/components/CursorTracker";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NeonBackground />
        <Toaster richColors position="top-center" />
        <CursorTracker />
        {children}
      </body>
    </html>
  );
}
